github:
  user: "GitHub Actions"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "github-actions"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "weekly"
  owner: "jenkins-docs"
  repository: "quickstart-tutorials"
